name: example
description: siri_wave demo
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  siri_wave:
    path: ../


flutter:
  uses-material-design: true
