name: Prepare Release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    uses: halildurmus/workflows/.github/workflows/prepare_release.yml@main
    with:
      use_flutter: true
    secrets:
      token: ${{ secrets.PAT }}
